# VSI/openenv only. Find prefix packages and alias them to the Conan target
# names the module CMakeLists files already link.

function(slideio_alias_if_missing dest src)
    if(NOT TARGET ${dest} AND TARGET ${src})
        add_library(${dest} INTERFACE IMPORTED GLOBAL)
        target_link_libraries(${dest} INTERFACE ${src})
    endif()
endfunction()

if(CMAKE_PREFIX_PATH)
    list(GET CMAKE_PREFIX_PATH 0 _prefix)
    foreach(_pkg IN ITEMS SQLite3 LibLZMA ICU)
        if(NOT ${_pkg}_ROOT)
            set(${_pkg}_ROOT "${_prefix}")
        endif()
    endforeach()
endif()

find_package(SQLite3 REQUIRED)
find_package(LibLZMA REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(OpenCV REQUIRED)
find_package(ZLIB REQUIRED)
find_package(tinyxml2 CONFIG REQUIRED)
find_package(nlohmann_json REQUIRED)
find_package(TIFF REQUIRED)
find_package(PNG REQUIRED)
find_package(WebP CONFIG REQUIRED)
find_package(libjpeg-turbo CONFIG REQUIRED)
find_package(FreeImage REQUIRED CONFIG)
find_package(lcms2 CONFIG REQUIRED)
find_package(ICU REQUIRED COMPONENTS uc i18n)

if(NOT OpenJPEG_DIR)
    foreach(_p IN LISTS CMAKE_PREFIX_PATH)
        file(GLOB _opj "${_p}/lib/cmake/openjpeg-*")
        if(_opj)
            list(GET _opj 0 OpenJPEG_DIR)
            break()
        endif()
    endforeach()
endif()
find_package(OpenJPEG REQUIRED CONFIG)

if(BUILD_TESTING)
    find_package(GTest CONFIG REQUIRED)
    slideio_alias_if_missing(gtest::gtest GTest::gtest)
    slideio_alias_if_missing(gtest::gtest_main GTest::gtest_main)
endif()

slideio_alias_if_missing(SQLite::SQLite3 SQLite3::SQLite3)
slideio_alias_if_missing(opencv::opencv opencv_world)
slideio_alias_if_missing(TIFF::TIFF TIFF::tiff)
slideio_alias_if_missing(libwebp::libwebp WebP::webp)
slideio_alias_if_missing(JPEG::JPEG libjpeg-turbo::jpeg)
slideio_alias_if_missing(lcms::lcms lcms2::lcms2)
slideio_alias_if_missing(freeimage::freeimage FreeImage::FreeImage)
if(NOT TARGET icu::icu)
    add_library(icu::icu INTERFACE IMPORTED GLOBAL)
    target_link_libraries(icu::icu INTERFACE ICU::uc ICU::i18n)
endif()
